[project]
name = "nfl-sim"
version = "0.1.0"
authors = [
    { name = "Tyler Riccio", email = "tylerriccio8@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "flask>=3.0.0",
    "jinja2>=3.1.6",
    "joblib>=1.5.3",
    "loguru>=0.7.3",
    "numpy>=2.0.0",
    "polars>=1.36.1",
    "pysuite>=0.1.0",
    "rich>=14.2.0",
    "treelite>=4.6.1",
    "xgboost>=3.2.0",
]

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
module-name = "nfl_sim"
module-root = ""

[tool.uv.sources]
pysuite = { git = "https://github.com/tylerriccio33/pysuite" }

[project.scripts]
nfl-sim = "nfl_sim.__main__:main"

[dependency-groups]
dev = [
    "complexipy>=5.1.0",
    "great-tables>=0.20.0",
    "hypothesis>=6.100.0",
    "line-profiler>=4.1.0",
    "nflreadpy>=0.1.5",
    "plotext>=5.3.2",
    "pysuite",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "pytest-randomly>=4.0.1",
    "pytest-timeout>=2.4.0",
    "requests>=2.32.5",
    "ruff>=0.14.10",
    "scikit-learn>=1.8.0",
    "tl2cgen>=1.0.0",
    "torchmetrics>=1.8.2",
    "ty>=0.0.8",
]

[tool.ruff]
line-length = 100
fix = true

[tool.ruff.lint]
select = [
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "D", # flake8-docstrings
  "D417", # undocumented-param
  "E", # pycodestyle
  "EM", # flake8-errmsg
  "F", # pyflakes
  "FBT001", # flake8-boolean-trap
  "I", # isort
  "ICN", # flake8-import-conventions
  "INT", # flake8-gettext
  "PERF", # perflint
  "PIE", # flake8-pie
  "PT", # flake8-pytest-style
  "PTH", # flake8-use-pathlib
  "PYI", # flake8-pyi
  "RUF", # ruff-specific rules
  "SIM", # flake8-simplify
  "TCH", # flake8-type-checking
  "TD", # flake8-todos
  "TID", # flake8-tidy-imports
  "TRY", # tryceratops
  "UP", # pyupgrade
  "W", # pycodestyle
  "ERA", # commented out code
  "ANN401", # No Any
  "ASYNC", # Flake8 async rules
  "S",
  "NPY", # NumPy style docstring rules
  "N", # Namings
  "PLC", # Pylint conventions
  "FURB", # Refurb
]

ignore = [
  "D401", # Relax NumPy docstring convention: first line should be imperative
  "E501", # Line length regulated by formatter
  "PT011", # pytest.raises is too broad, set match or use a more specific exception
  "PYI041", # Use float instead of int | float
  "RUF022", # `__all__` is not sorted
  "RUF005", # Consider expression instead of concatenation
  "SIM102", # Use a single `if` statement instead of nested `if` statements
  "SIM108", # Use ternary operator
  "SIM114", # Combine `if` branches
  "TD002", # Missing author in TODO
  "TD003", # Missing issue link on the line following this TODO
  "TRY003", # Avoid specifying long messages outside the exception class
  "B905",
  "D105",
  "FBT001",
  "EM101",
  "D203",
  "EM102",
  "D213",
  "D107",
  "S101", # Use assert
  "S105" # Secret keys
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D100", "D102", "D103", "B018", "F841", "FBT001"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "@overload",
  "except ImportError",
  "if TYPE_CHECKING:",
  "from typing_extensions import ",
  "def __repr__(self) -> str:"
]
