"""State variables that determine the settings of the game are here."""

from dataclasses import dataclass
from enum import Enum, auto

type TeamId = str


@dataclass(frozen=True)
class GameState:
    """What the rules care about NOW.

    This is the minimal Markov state needed to advance the game.
    If removing a field would change the next-play distribution, it belongs here.
    GameState is rules-complete, not information-complete
    """

    quarter: int
    clock: int  # seconds remaining in quarter
    offense: TeamId
    defense: TeamId
    down: int
    distance: int
    yardline: int  # yards from endzone
    score: tuple[int, int]
    possession_id: int


class Action(Enum):
    """What the offense chooses to do; decision not the outcome."""

    RUN = auto()
    PASS = auto()
    FIELD_GOAL = auto()
    PUNT = auto()


class TurnoverType(Enum):
    """Type of turnover generated by the outcome model.

    Note: Turnover on downs is NOT here - it's a state machine rule (4th down failure),
    not a model-generated outcome.
    """

    NONE = auto()
    INTERCEPTION = auto()
    FUMBLE = auto()


@dataclass
class Outcome:
    """Decision/play outcome itself. Used to calculate future GameState."""

    yards: int
    turnover_type: TurnoverType
    touchdown: bool
    time_elapsed: int

    @property
    def turnover(self) -> bool:
        """Backward compat - True if any turnover occurred."""
        return self.turnover_type != TurnoverType.NONE


@dataclass
class PlayEvent:
    """Log of the play that took place.

    This is not part of the state machine.
    """

    state_before: GameState
    action: Action
    outcome: Outcome
    state_after: GameState


GameTrace = list[PlayEvent]
"""What the model cares about; append only log."""
