"""State variables that determine the settings of the game are here."""

from dataclasses import dataclass
from enum import Enum, auto
from typing import NamedTuple

type TeamId = str

# ---------------------------------------------------------------------------
# _GameState: plain tuple used in the hot loop for zero-overhead construction.
#
# Layout (index constants below):
#   (quarter, clock, offense, defense, down, distance, yardline, score, possession_id)
#
# GameState (NamedTuple) is the public API; _GameState is the internal
# representation returned by apply_outcome and consumed by the game loop.
# ---------------------------------------------------------------------------

_Q = 0  # quarter
_CLK = 1  # clock (seconds remaining in quarter)
_OFF = 2  # offense TeamId
_DEF = 3  # defense TeamId
_DN = 4  # down
_DIST = 5  # distance
_YL = 6  # yardline (yards from endzone)
_SC = 7  # score  (home, away)
_PID = 8  # possession_id

type _GameState = tuple[int, int, TeamId, TeamId, int, int, int, tuple[int, int], int]


class GameState(NamedTuple):
    """What the rules care about NOW.

    This is the minimal Markov state needed to advance the game.
    If removing a field would change the next-play distribution, it belongs here.
    GameState is rules-complete, not information-complete

    This should be as minimal as possible, it's copied in the hottest loops.
    """

    quarter: int
    clock: int  # seconds remaining in quarter
    offense: TeamId
    defense: TeamId
    down: int
    distance: int
    yardline: int  # yards from endzone
    score: tuple[int, int]
    possession_id: int  # TODO: Unlikely we need this


class Action(Enum):
    """What the offense chooses to do; decision not the outcome."""

    RUN = auto()
    PASS = auto()
    FIELD_GOAL = auto()
    PUNT = auto()


class TurnoverType(Enum):
    """Type of turnover generated by the outcome model.

    Note: Turnover on downs is NOT here - it's a state machine rule (4th down failure),
    not a model-generated outcome.
    """

    NONE = auto()
    INTERCEPTION = auto()
    FUMBLE = auto()


@dataclass
class Outcome:
    """Decision/play outcome itself. Used to calculate future GameState."""

    yards: int
    turnover_type: TurnoverType
    touchdown: bool
    time_elapsed: int

    @property
    def turnover(self) -> bool:
        """Backward compat - True if any turnover occurred."""
        return self.turnover_type != TurnoverType.NONE


@dataclass  # TODO: Frozen?
class PlayEvent:
    """Log of the play that took place.

    This is not part of the state machine.
    """

    state_before: _GameState
    action: Action
    outcome: Outcome
    state_after: _GameState


GameTrace = list[PlayEvent]
"""What the model cares about; append only log."""
