"""State variables that determine the settings of the game are here."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto
from typing import Literal

type TeamId = Literal["HOME", "AWAY"]

# ---------------------------------------------------------------------------
# _GameState: plain tuple used in the hot loop for zero-overhead construction.
#
# Layout (index constants below):
# quarter, clock, offense, defense, down, distance, yardline_100, score
#
# _GameState is returned by apply_outcome and consumed by the game loop.
# ---------------------------------------------------------------------------
_Q = 0  # quarter
_CLK = 1  # clock (seconds remaining in quarter)
_OFF = 2  # offense TeamId
_DEF = 3  # defense TeamId
_DN = 4  # down
_DIST = 5  # distance
_YL = 6  # yardline_100 (yards from endzone)
_SC = 7  # score  (home, away)

type _GameState = tuple[int, int, TeamId, TeamId, int, int, int, tuple[int, int]]


class Intent(Enum):
    """What the offense chooses to do; decision not the outcome."""

    RUN = 1
    DROPBACK = 2
    FIELD_GOAL = 3
    PUNT = 4


class Route(Enum):
    """Routing key that selects which outcome sub-model to use."""

    RUN = 1
    DROPBACK = 2
    ST = 3  # special teams (punt, field goal)


class TurnoverType(Enum):
    """Type of turnover generated by the outcome model.

    Note: Turnover on downs is NOT here - it's a state machine rule (4th down failure),
    not a model-generated outcome.
    """

    NONE = auto()
    INTERCEPTION = auto()
    FUMBLE = auto()


from nfl_sim.engine._GENERATED_outcome import Outcome as Outcome  # noqa: E402, PLC0414, TC001


@dataclass(frozen=True)
class PlayEvent:
    """Log of the play that took place.

    This is not part of the state machine.
    """

    state_before: _GameState
    intent: Intent
    outcome: Outcome
    state_after: _GameState


type GameTrace = list[PlayEvent]
"""What the model cares about; append only log."""
