"""Generate _agg_types.pyi stub file from EXPR.py expression schemas.

Run via: make types
"""

from pathlib import Path

import polars as pl

from nfl_sim.summarize._agg_types import _game_schema, _team_schema

STUB_PATH = Path(__file__).resolve().parent.parent / "nfl_sim" / "summarize" / "_agg_types.pyi"

assert STUB_PATH.exists()


def _map_dtype(dtype: pl.DataType) -> str:
    """Map a polars DataType to a Python type annotation string."""
    if isinstance(dtype, pl.Float64):
        return "float"
    if isinstance(
        dtype, (pl.Int8, pl.Int16, pl.Int32, pl.Int64, pl.UInt8, pl.UInt16, pl.UInt32, pl.UInt64)
    ):
        return "int"
    if isinstance(dtype, pl.Boolean):
        return "bool"
    if isinstance(dtype, (pl.String, pl.Utf8)):
        return "str"
    if isinstance(dtype, pl.List):
        inner = _map_dtype(dtype.inner)  # type: ignore[arg-type]
        return f"list[{inner}]"
    return "Any"


def _generate_class(name: str, schema: pl.Schema) -> list[str]:
    """Generate a NamedTuple class definition from a polars Schema."""
    lines = [f"class {name}(NamedTuple):"]
    for field_name in schema.names():
        py_type = _map_dtype(schema[field_name])
        lines.append(f"    {field_name}: {py_type}")
    return lines


def main() -> None:
    """Generate the _agg_types.pyi stub file with typed NamedTuple definitions."""
    # Check if we need the Any import
    all_types = [_map_dtype(_game_schema[n]) for n in _game_schema.names()]
    all_types += [_map_dtype(_team_schema[n]) for n in _team_schema.names()]
    needs_any = "Any" in all_types

    # Build stub content
    lines = ["# AUTO-GENERATED by scripts/gen_agg_stubs.py — do not edit manually", ""]
    if needs_any:
        lines.append("from typing import Any, NamedTuple")
    else:
        lines.append("from typing import NamedTuple")
    lines.append("")
    lines.append("import polars as pl")
    lines.append("")

    # Expose private schemas used by the stub generator itself
    lines.append("_game_schema: pl.Schema")
    lines.append("_team_schema: pl.Schema")
    lines.append("")

    lines.extend(_generate_class("GameAggs", _game_schema))
    lines.append("")
    lines.extend(_generate_class("TeamAggs", _team_schema))
    lines.append("")

    STUB_PATH.write_text("\n".join(lines))
    print(f"Generated {STUB_PATH}")


if __name__ == "__main__":
    main()
